[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "7.0"
opencv = "0.88"
tokio = { version = "1.0", features = ["full"] }
rayon = "1.10"
candle-core = "0.8"
candle-nn = "0.8"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
